import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./_styles/globals.css";
import { createTheme, CssBaseline, ThemeProvider } from "@mui/material";
import ThemeRegistry from "./providers/ThemeRegistry";
import { StoreProvider } from "./_store/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme = createTheme({
  typography: {
    fontFamily: ["Poppins", "sans-serif"].join(","),
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeRegistry>{children}</ThemeRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
